name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Fazer checkout do código
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Instalar Node.js (usado pelo Oryx)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build e deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WAVE_0F8F1371E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "hotel-solicitacoes-frontend"       # pasta do frontend
          api_location: ""                                  # sem API integrada
          output_location: "hotel-solicitacoes-frontend/dist"  # pasta gerada pelo build do Vite
          #### Variáveis de ambiente do frontend
          env:
            VITE_API_URL: "https://hotel-api.azurewebsites.net"  # substitua pelo seu backend real

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WAVE_0F8F1371E }}
          action: "close"